title:            tklarryonline.me
description:      thinking and hacking
url:              tklarryonline.github.io
signoff:          Luan Nguyen Thanh
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links: 
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://tklarryonline.github.io
  - name:         Email
    url:          mailto:luan.nguyenthanh@tklarryonline.me
  - name:         GitHub
    url:          http://github.com/tklarryonline

pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
